codingstyle according to shfmt

diff --git a/ocspverify b/ocspverify
--- a/ocspverify
+++ b/ocspverify
@@ -9,11 +9,11 @@ ocsp_url=$(echo "${cert_parsed}" | grep "OCSP - URI" | sed -e 's/.*URI://g')
 ocsp_host=$(echo "${ocsp_url}" | sed -e 's:.*//::g' -e 's:/.*::g')
 
 # Getting AIA issuer certificate and converting it to PEM
-! wget -q -O "${TMP}/issuer.der" "${issuer_url}" \
-	&& echo "ERROR: Failed fetching intermediate" && exit 1
+! wget -q -O "${TMP}/issuer.der" "${issuer_url}" &&
+	echo "ERROR: Failed fetching intermediate" && exit 1
 
-! openssl x509 -inform der -in "${TMP}/issuer.der" -outform pem -out "${TMP}/issuer.pem" \
-	&& echo "ERROR: Failed to parse intermediate" && exit 1
+! openssl x509 -inform der -in "${TMP}/issuer.der" -outform pem -out "${TMP}/issuer.pem" &&
+	echo "ERROR: Failed to parse intermediate" && exit 1
 
 openssl verify "${TMP}/issuer.pem" | grep error
 [ $? -eq 0 ] && echo "WARNING: Couldn't verify issuer certificate"
